# Generated by Django 5.2.6 on 2025-09-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_rating_product_return_policy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='warranty',
            new_name='contact_info',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='return_policy',
            new_name='instagram_caption',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='reviews_count',
            new_name='instagram_comments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='source',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='instagram_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram_post_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='is_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
