# Generated by Django 5.2.6 on 2025-09-18 16:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_product_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('platform_url', models.URLField(max_length=1000, unique=True)),
                ('in_stock', models.BooleanField(db_index=True, default=True)),
                ('stock_quantity', models.IntegerField(blank=True, db_index=True, null=True)),
                ('stock_status', models.CharField(blank=True, max_length=100)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shipping_time', models.CharField(blank=True, max_length=100)),
                ('free_shipping', models.BooleanField(db_index=True, default=False)),
                ('warranty_period', models.CharField(blank=True, max_length=100)),
                ('return_policy', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('features', models.JSONField(blank=True, default=list)),
                ('average_rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('review_count', models.IntegerField(db_index=True, default=0)),
                ('original_category_path', models.CharField(blank=True, max_length=500)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('scraping_source', models.CharField(default='selenium', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('post_url', models.URLField(max_length=500)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True, help_text='Comma-separated hashtags')),
                ('likes_count', models.IntegerField(db_index=True, default=0)),
                ('comments_count', models.IntegerField(db_index=True, default=0)),
                ('engagement_rate', models.FloatField(blank=True, db_index=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_story', models.BooleanField(default=False)),
                ('is_reel', models.BooleanField(default=False)),
                ('contact_info', models.CharField(blank=True, max_length=300)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('scraping_source', models.CharField(default='apify', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('platform_type', models.CharField(choices=[('social', 'Social Media'), ('ecommerce', 'E-commerce'), ('marketplace', 'Marketplace')], db_index=True, max_length=20)),
                ('base_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('scraping_enabled', models.BooleanField(default=True)),
                ('rate_limit_per_hour', models.IntegerField(default=100)),
                ('requires_authentication', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('change_source', models.CharField(choices=[('scraping', 'Scraping'), ('manual', 'Manual Update'), ('api', 'API Update')], default='scraping', max_length=20)),
                ('price_change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_change_percentage', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('scraped', 'Scraped')], db_index=True, max_length=20)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('change_source', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('main_category', models.CharField(db_index=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, max_length=50)),
                ('color_code', models.CharField(blank=True, max_length=7)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for product matching')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('product_count', models.IntegerField(db_index=True, default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['main_category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('is_verified_purchase', models.BooleanField(db_index=True, default=False)),
                ('helpful_votes', models.IntegerField(db_index=True, default=0)),
                ('is_approved', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('source_url', models.URLField(max_length=1000)),
                ('scraper_type', models.CharField(db_index=True, max_length=50)),
                ('raw_json', models.JSONField()),
                ('raw_html', models.TextField(blank=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_errors', models.JSONField(blank=True, default=list)),
                ('retry_count', models.IntegerField(default=0)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=250)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=20)),
                ('contact_address', models.TextField(blank=True)),
                ('profile_url', models.URLField(blank=True)),
                ('profile_image_url', models.URLField(blank=True)),
                ('follower_count', models.IntegerField(db_index=True, default=0)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('brand', 'Brand'), ('reseller', 'Reseller')], db_index=True, default='individual', max_length=20)),
                ('response_rate', models.FloatField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('total_products', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-follower_count', 'display_name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='notify_back_in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='notify_price_drop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['name', 'is_verified'], name='products_br_name_7a5e77_idx'), models.Index(fields=['slug'], name='products_br_slug_d4d839_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='products_br_search__562fcc_gin')],
            },
        ),
        migrations.CreateModel(
            name='CoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(db_index=True, default='PKR', max_length=3)),
                ('model_number', models.CharField(blank=True, db_index=True, max_length=150)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('main_image_url', models.URLField(blank=True, max_length=1000)),
                ('platform_type', models.CharField(choices=[('instagram', 'Instagram'), ('ecommerce', 'E-commerce'), ('marketplace', 'Marketplace')], db_index=True, max_length=20)),
                ('view_count', models.IntegerField(db_index=True, default=0)),
                ('wishlist_count', models.IntegerField(db_index=True, default=0)),
                ('quality_score', models.FloatField(db_index=True, default=0.0, help_text='Calculated quality score based on data completeness and seller reputation', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to='products.coreproduct'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'added_at'], name='products_wi_user_id_29c868_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['product', 'added_at'], name='products_wi_product_d2091c_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['priority', 'added_at'], name='products_wi_priorit_b063d5_idx'),
        ),
        migrations.AddField(
            model_name='ecommerceproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_data', to='products.coreproduct'),
        ),
        migrations.AddField(
            model_name='instagramproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_data', to='products.coreproduct'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['platform_type', 'is_active'], name='products_pl_platfor_032495_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['name', 'platform_type'], name='products_pl_name_67a2d8_idx'),
        ),
        migrations.AddField(
            model_name='ecommerceproduct',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_products', to='products.platform'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.coreproduct'),
        ),
        migrations.AddField(
            model_name='productauditlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='products.coreproduct'),
        ),
        migrations.AddField(
            model_name='productauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.coreproduct'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawscrapeddata',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='products.platform'),
        ),
        migrations.AddField(
            model_name='rawscrapeddata',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_data', to='products.coreproduct'),
        ),
        migrations.AddField(
            model_name='seller',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='products.platform'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.seller'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
