# Generated by Django 5.2.6 on 2025-09-18 16:45

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ecommerceproduct_instagramproduct_platform_and_more'),
        ('recommendations', '0002_alter_recommendation_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddIndex(
            model_name='instagramproduct',
            index=models.Index(fields=['post_id'], name='products_in_post_id_b75643_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramproduct',
            index=models.Index(fields=['likes_count', 'comments_count'], name='products_in_likes_c_ce2fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramproduct',
            index=models.Index(fields=['engagement_rate'], name='products_in_engagem_33b872_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramproduct',
            index=models.Index(fields=['posted_at'], name='products_in_posted__00343f_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramproduct',
            index=models.Index(fields=['last_scraped'], name='products_in_last_sc_021a01_idx'),
        ),
        migrations.AddIndex(
            model_name='ecommerceproduct',
            index=models.Index(fields=['platform', 'in_stock'], name='products_ec_platfor_21959b_idx'),
        ),
        migrations.AddIndex(
            model_name='ecommerceproduct',
            index=models.Index(fields=['platform_product_id'], name='products_ec_platfor_53797e_idx'),
        ),
        migrations.AddIndex(
            model_name='ecommerceproduct',
            index=models.Index(fields=['stock_quantity'], name='products_ec_stock_q_684d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='ecommerceproduct',
            index=models.Index(fields=['average_rating', 'review_count'], name='products_ec_average_e6f231_idx'),
        ),
        migrations.AddIndex(
            model_name='ecommerceproduct',
            index=models.Index(fields=['free_shipping'], name='products_ec_free_sh_1bfc17_idx'),
        ),
        migrations.AddIndex(
            model_name='ecommerceproduct',
            index=models.Index(fields=['last_scraped'], name='products_ec_last_sc_f9794f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ecommerceproduct',
            unique_together={('platform', 'platform_product_id')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'recorded_at'], name='products_pr_product_045f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['recorded_at'], name='products_pr_recorde_b1d7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['price'], name='products_pr_price_9d604b_idx'),
        ),
        migrations.AddIndex(
            model_name='productauditlog',
            index=models.Index(fields=['product', 'timestamp'], name='products_pr_product_686d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='productauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='products_pr_action_653001_idx'),
        ),
        migrations.AddIndex(
            model_name='productauditlog',
            index=models.Index(fields=['timestamp'], name='products_pr_timesta_22dc07_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['main_category', 'subcategory'], name='products_pr_main_ca_b84aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent', 'is_active', 'sort_order'], name='products_pr_parent__859a80_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_featured', 'product_count'], name='products_pr_is_feat_a6c9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'is_approved', 'created_at'], name='products_pr_product_68fcc8_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating', 'is_approved'], name='products_pr_rating_6aa464_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['helpful_votes'], name='products_pr_helpful_f934d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user')},
        ),
        migrations.AddIndex(
            model_name='rawscrapeddata',
            index=models.Index(fields=['platform', 'processed', 'scraped_at'], name='products_ra_platfor_b58025_idx'),
        ),
        migrations.AddIndex(
            model_name='rawscrapeddata',
            index=models.Index(fields=['scraper_type', 'processed'], name='products_ra_scraper_53659a_idx'),
        ),
        migrations.AddIndex(
            model_name='rawscrapeddata',
            index=models.Index(fields=['source_url'], name='products_ra_source__03796a_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['platform', 'username'], name='products_se_platfor_0b951e_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['platform', 'verified', 'is_active'], name='products_se_platfor_036f02_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['business_type', 'average_rating'], name='products_se_busines_291339_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['follower_count'], name='products_se_followe_160e99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together={('platform', 'username')},
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=models.Index(fields=['platform_type', 'is_active', 'created_at'], name='products_co_platfor_7b81c7_idx'),
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=models.Index(fields=['category', 'brand', 'price'], name='products_co_categor_14bc55_idx'),
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=models.Index(fields=['seller', 'is_active'], name='products_co_seller__55720a_idx'),
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=models.Index(fields=['price', 'currency'], name='products_co_price_f93194_idx'),
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=models.Index(fields=['is_featured', 'quality_score'], name='products_co_is_feat_9e0225_idx'),
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=models.Index(fields=['brand', 'category'], name='products_co_brand_i_7a76a6_idx'),
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=models.Index(fields=['name', 'brand'], name='products_co_name_619202_idx'),
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=models.Index(fields=['model_number'], name='products_co_model_n_a9c7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=models.Index(fields=['sku'], name='products_co_sku_a359d3_idx'),
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=models.Index(fields=['created_at', 'platform_type'], name='products_co_created_7fbb70_idx'),
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=models.Index(fields=['view_count'], name='products_co_view_co_de9a23_idx'),
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=models.Index(fields=['wishlist_count'], name='products_co_wishlis_a29c56_idx'),
        ),
        migrations.AddIndex(
            model_name='coreproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='products_co_search__040146_gin'),
        ),
    ]
