# Generated by Django 5.2.6 on 2025-09-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='url',
            field=models.URLField(blank=True, help_text='Category URL for scraping'),
        ),
    ]
