# Generated by Django 5.2.6 on 2025-10-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcategory_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreproduct',
            name='search_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
