# Generated by Django 5.2.6 on 2025-10-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_coreproduct_search_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreproduct',
            name='availability_check_message',
            field=models.TextField(blank=True, help_text='Message to show users when product is unavailable'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='availability_status',
            field=models.CharField(choices=[('active', 'Active - Available on platform'), ('checking', 'Checking - Availability being verified'), ('unavailable', 'Unavailable - Not found on platform'), ('error', 'Error - Could not verify'), ('unknown', 'Unknown - Not checked yet')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='consecutive_failures',
            field=models.IntegerField(default=0, help_text='Number of consecutive failed availability checks'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='last_availability_check',
            field=models.DateTimeField(blank=True, help_text='Last time we checked if product exists on source platform', null=True),
        ),
    ]
