# Generated by Django 5.2.6 on 2025-09-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ecommerceproduct_instagramproduct_platform_and_more'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='products.coreproduct'),
        ),
    ]
